# Generated by Django 3.2.6 on 2023-10-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
