# Generated by Django 3.2.6 on 2023-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20231019_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('house_name', models.CharField(max_length=100)),
                ('plant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
