# Generated by Django 3.2.6 on 2023-10-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20231019_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_list',
            new_name='users',
        ),
    ]
