# Generated by Django 3.2.6 on 2023-10-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_user_list_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cars',
        ),
    ]
