# Generated by Django 3.2.6 on 2023-10-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
