# Generated by Django 3.2.6 on 2023-10-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
