# Generated by Django 3.2.6 on 2023-10-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('houseName', models.CharField(max_length=100)),
                ('plantName', models.CharField(max_length=100)),
            ],
        ),
    ]
