# Generated by Django 3.2.6 on 2023-10-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='users',
            name='isActive',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
