# Generated by Django 3.2.6 on 2023-10-25 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20231025_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isActive',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
