# Generated by Django 3.2.6 on 2023-10-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_users_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
