# Generated by Django 3.2.6 on 2023-10-27 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_users_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
