# Generated by Django 3.2.6 on 2023-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20231027_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createdBy',
            field=models.IntegerField(default=1, max_length=1000),
        ),
        migrations.AddField(
            model_name='users',
            name='updatedBy',
            field=models.IntegerField(default=1, max_length=1000),
        ),
    ]
