# Generated by Django 3.2.6 on 2023-10-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20231030_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='createdBy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedBy',
            field=models.IntegerField(default=1),
        ),
    ]
