# Generated by Django 3.2.6 on 2023-11-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20231116_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_required', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=255)),
                ('createdBy', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.IntegerField(default=1)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
