# Generated by Django 3.2.6 on 2023-11-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='time_required',
            field=models.CharField(max_length=8),
        ),
    ]
