# Generated by Django 3.2.6 on 2023-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20231121_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='mapped_under',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
