# Generated by Django 3.2.6 on 2023-11-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20231122_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
