# Generated by Django 3.2.6 on 2023-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_expiration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
