# Generated by Django 3.2.6 on 2023-12-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_profile_token_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
