# Generated by Django 3.2.6 on 2023-12-05 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('companay_address', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
