# Generated by Django 3.2.6 on 2023-12-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20231205_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companay_address',
            new_name='company_address',
        ),
    ]
