# Generated by Django 3.2.6 on 2023-12-08 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0015_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=255)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('total_line_count', models.IntegerField(default=0)),
                ('total_pole_count', models.IntegerField(default=0)),
                ('total_leds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='authentication.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pole_count', models.PositiveIntegerField(default=0)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='authentication.house')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_required', models.CharField(max_length=8)),
                ('remarks', models.CharField(max_length=255)),
                ('createdBy', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedBy', models.IntegerField(default=1)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rasp',
            fields=[
                ('rbi', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('pole_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('led_count', models.PositiveIntegerField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poles', to='authentication.line')),
            ],
        ),
        migrations.CreateModel(
            name='LED',
            fields=[
                ('led_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('is_on', models.BooleanField(default=False)),
                ('button_no', models.PositiveIntegerField(unique=True)),
                ('led_on_date', models.DateTimeField(blank=True, null=True)),
                ('led_off_date', models.DateTimeField(blank=True, null=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leds', to='authentication.pole')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.plant'),
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('raspberry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raspberry_instances', to='authentication.rasp')),
            ],
            options={
                'unique_together': {('date', 'raspberry_id')},
            },
        ),
    ]
