# Generated by Django 3.2.6 on 2023-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20231208_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
