# Generated by Django 3.2.6 on 2023-12-13 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0017_farm_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='led',
            name='button_no',
            field=models.PositiveIntegerField(),
        ),
    ]
