# Generated by Django 3.2.6 on 2023-12-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20231213_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='rasp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led', to='authentication.rasp'),
        ),
    ]
