# Generated by Django 3.2.6 on 2023-12-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_led_rasp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='rasp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led', to='authentication.rasp'),
        ),
    ]
