# Generated by Django 3.2.6 on 2023-12-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_led_rasp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasp',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
