# Generated by Django 3.2.6 on 2023-12-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_rasp_is_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasp',
            name='is_assigned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
