# Generated by Django 3.2.6 on 2024-01-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_rasp_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasp',
            name='rasp_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
