# Generated by Django 3.2.6 on 2024-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_rasp_rasp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='button_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
